print('Treinos de Academia ')
Emagrecimento = str(input('Escolha um treino que melhore  seu perfio físico são eles:\n Emagrecimento (1) ou Hipertrofia (2)\n'))
if Emagrecimento == '1':
    print('Ok Seu treino consiste em um objetivo voltado a queima de gordura então são eles:')
    print('Alongamento de 30 segundos para todos os membros superiores e inferiores')
    print('3 séries de 20 polichinelos')
    print('3 séries de 20 adominais')
    print('3 séries de 20 agachamentos simples com 10 seguntos de descanso')
    print('3 séries de 20 burpee com 20 segundos de descanso')
    print('Repitir toda semana os mesmo exercicios durante 1 mês2')
else :
    print('Ok seu treino consiste em um objetivo de Ganho de massa\nCom 5 dias de treinos de força e 1 dia de treino de Cárdio')
    print('Alongamento de 30 segundos para todos os membros superiores e inferiores')
    print('treino A B C D')
print('Qual dia da semana você quer saber ?')
print('Segunda (1) Terça (2) quarta (3) quinta(4)')
dia = str(input(':'))
if dia == '1':
    print('Segunda')
    print(' Agachamento livre 3 séries de 12 repetições')
    print(' Leg press 3 séries de 15 repetições')
    print(' posterior com 3 séries de 15 repeições')
    print(' cadeira flexora 3 séries de 15 repetições')
    print(' Panturrilha 4 séries de 15 repetições no step com ou sem alteres')
elif dia == '2':
    print('Terça feira')
    print('Treino de ombro e costa')
    print('Elevação lateral 3 séries de 15 repetições')
    print('Militar com barra 3 séries de 12 repetições ')
    print('puxada frontal alta na polia 4 séries de 12 repetições ')
    print('Remada baixa 3 séries de 15 repetições ')
    print('Pulldown 3 séries de 15 repetições ')
elif dia == '3':
    print('Quarta')
    print('Treino de peito')
    print('Supino reto 3 séries de 12 a 15 repetições')
    print('Supino inclinado 3 séries de 12 repetições')
    print('Crossover 4 séries de 12 repetições')
    print('Peck Deck voador 4 séries de 12 a 15 repetições')
    print('Repitir toda semana os mesmo exercicios durante 1 mês ')
elif dia == '4':
    print('Quinta')
    print('Treino de bíceps e Tríceps')
    print('Rosca direta 4 Séries de 12 repetições')
    print('Rosca Martelo cruzado 3 séries e 15 repetições')
    print('Rosca Scott 3 séries de 15 repetições')
    print('Triceps testa 3 séries de 15 repetições')
    print('Triceps Pulley 4 séries de 12 repetições')
    print('Tricepe na corada 3 séries de 15 reprtições')
str(input('gostaria de saber mais algum dia da semana ?\n'))



print('Obrigado e uma boa semana de treinos '.format(Emagrecimento))
